# Generated by Django 5.1.3 on 2024-11-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Course_Number', models.IntegerField()),
                ('Instructor_Name', models.CharField(max_length=50)),
                ('Duration', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'UniversityClasses',
            },
        ),
    ]
